spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/desafio
        username: root
        password: 123456
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: postgresql
